# Google Gemini API Key
GOOGLE_API_KEY = "DEIN_GEMINI_API_KEY_HIER"

# Google Auth
[google]
client_id = "778493291610-75iipmg0bcpr8g6d374bbdgetub8a1eu.apps.googleusercontent.com"
client_secret = "GOCSPX-plZkSP3jivzuVOr9>ZLTywzcxmcr"
redirect_uri = "https://blop-study.streamlit.app/"